name: Linux

on:
  push:
    branches:
      - master
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository (submodules by cmake)
      uses: actions/checkout@v2

    - name: Compilation check
      run: |
        cmake .
        make clean
        make
